baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Dũng Học Giỏi'
theme = 'LoveIt'
#publishdir = "du4ng.github.io"
[params]
favicon = '/static/favicon.ico'

[author]
name = "mấythằng.ml | Software Engineer"

[languages.en.params.home.profile]
enable = true
avatarURL = "/avatar.png"
title = "If the code works"
subtitle = "DON'T touch it"
typeit = false
social = true
